### ISSUE TITLE
Training / Validation / Test split contamination

### ISSUE THREAD

**Issue by AndersonHappens** [BrunoCLR/MolGen_Opt#1]
The molecules in the "All" training split are not the same as the molecules in the training splits for each individual scent (and same for the validation and test splits). 

This is a problem if someone decides to train on the "all" split first and then fine-tune on training split for individual scents (like the authors did in this paper https://arxiv.org/pdf/2402.12134.pdf), as they are unknowingly testing and validating on molecules they trained on. 

For instance, the molecule "CCCCCCCCCC=O" shows up in the "All" validation split, but doesn't show up in the "Citrus" validation split. Instead, it shows up in the "Citrus" training split.

**Comment by BrunoCLR** [comment]
The same molecules were indeed used for general training of the model and testing/validation
in the transfer learning phases. Some identical molecules were also present in both the
test and validation datasets for each fragrance note. The datasets have now been updated to ensure there is no overlap between testing/validation data and training data.
